### ISSUE TITLE
3.0.0 - Could not find the requested service dnf-automatic-reboot.timer: host

### ISSUE THREAD

**Issue by gygitlab** [exploide/ansible-role-dnf-automatic#5]
Just wanted to let you know after updating to 3.0.0 we got the following error:

```
TASK [exploide.dnf-automatic : Install dnf-automatic package] ******************
ok: [machine-1]
TASK [exploide.dnf-automatic : Deploy dnf-automatic configuration file] ********
ok: [machine-1]
TASK [exploide.dnf-automatic : Start and enable systemd timer for dnf-automatic] ***
ok: [machine-1]
TASK [exploide.dnf-automatic : Set timer state for auto reboot] ****************
fatal: [machine-1]: FAILED! => changed=false 
  msg: 'Could not find the requested service dnf-automatic-reboot.timer: host'
```

We're no longer using the role but thought you'd want to know. Thanks.

**Comment by exploide** [comment]
Sorry for the inconvenience, should be fixed now.

**Comment by jlllopez** [comment]
Hi! Adding a task to install dnf-automatic package at the beginning of the role fixed it for me.
```
- name: Install dnf automatic
  dnf:
    name: dnf-automatic
```

**Comment by exploide** [comment]
I don't think this is related to the original issue which got fixed two years ago.

Besides, the role should already install the `dnf-automatic` package.

https://github.com/exploide/ansible-role-dnf-automatic/blob/89056174bb4a12f47036e9e862feb94d52f6ef67/tasks/main.yml#L3-L6

**Comment by jlllopez** [comment]
For me the `ansible.builtin.package` was not working as it should for some reason, the task succeeded but then I was getting the `msg: 'Could not find the requested service dnf-automatic-reboot.timer: host'` error. I dont think it is an issue with your module but using `dnf` instead of `package` worked for me. Just wrote it in case other people have this error including future me :smiley: 
Thank you very much for this role and your active support.
